import { q, SeedQ } from "./helpers";

export const biology: SeedQ[] = [
  // ---------------- SS1 ----------------
  q("SS1", 1, "The Cell", "The organelle described as the powerhouse of the cell is the _____.",
    ["mitochondrion", "nucleus", "ribosome", "lysosome"], 0,
    "Cellular respiration occurs in the mitochondria, where energy (ATP) is released.", "easy"),
  q("SS1", 1, "The Cell", "Which of the following structures is found in plant cells but NOT in animal cells?",
    ["chloroplast", "mitochondrion", "cell membrane", "cytoplasm"], 0,
    "Chloroplasts (like cellulose cell walls and large vacuoles) occur only in plant cells.", "easy"),
  q("SS1", 1, "Living Things", "Which of the following is NOT a characteristic of living things?",
    ["rusting", "respiration", "growth", "irritability"], 0,
    "Rusting is a chemical change in metals; the standard characteristics are Movement, Respiration, Nutrition, Irritability, Growth, Excretion, Reproduction and Death (MR NIGER D).", "easy"),
  q("SS1", 2, "Classification", "The binomial system of naming organisms was introduced by _____.",
    ["Carolus Linnaeus", "Charles Darwin", "Gregor Mendel", "Robert Hooke"], 0,
    "Linnaeus devised the two-name (genus + species) system of nomenclature."),
  q("SS1", 2, "Classification", "Bacteria are placed in the kingdom _____.",
    ["Monera (Prokaryotae)", "Protista", "Fungi", "Plantae"], 0,
    "The five-kingdom scheme puts unicellular prokaryotes - the bacteria - in Monera."),
  q("SS1", 2, "Microscopy", "A microscope with an eyepiece of \u00d710 and an objective lens of \u00d740 gives a total magnification of _____.",
    ["\u00d7400", "\u00d750", "\u00d740", "\u00d7410"], 0,
    "Total magnification = eyepiece \u00d7 objective = 10 \u00d7 40 = \u00d7400.", "easy"),
  q("SS1", 3, "Cell Theory", "The cell theory states that the cell is the basic unit of _____.",
    ["structure and function of living things", "the atom", "energy transfer", "heredity only"], 0,
    "All living organisms are made of cells, and the cell is the smallest unit capable of carrying out life processes."),
  q("SS1", 3, "Unicellular Organisms", "An example of a unicellular organism is _____.",
    ["Amoeba", "earthworm", "spirogyra", "hydra"], 0,
    "Amoeba (like Paramecium and Euglena) is a single-celled protozoan; the others are multicellular.", "easy"),

  // ---------------- SS2 ----------------
  q("SS2", 1, "Photosynthesis", "The gas released as a by-product of photosynthesis is _____.",
    ["oxygen", "carbon(IV) oxide", "nitrogen", "hydrogen"], 0,
    "6CO\u2082 + 6H\u2082O \u2192 C\u2086H\u2081\u2082O\u2086 + 6O\u2082 - oxygen is released from the splitting of water.", "easy"),
  q("SS2", 1, "Photosynthesis", "The site of photosynthesis in a green plant cell is the _____.",
    ["chloroplast", "mitochondrion", "nucleus", "vacuole"], 0,
    "Chlorophyll trapped in the chloroplasts absorbs the light energy that drives photosynthesis."),
  q("SS2", 2, "Digestion", "The enzyme in saliva that begins the digestion of starch is _____.",
    ["amylase (ptyalin)", "pepsin", "lipase", "trypsin"], 0,
    "Salivary amylase converts cooked starch to maltose in the mouth."),
  q("SS2", 2, "Digestion", "The end products of the digestion of proteins are _____.",
    ["amino acids", "fatty acids and glycerol", "glucose", "maltose"], 0,
    "Proteins \u2192 polypeptides \u2192 amino acids; fatty acids and glycerol come from lipids, glucose from starch."),
  q("SS2", 3, "Transport System", "In mammals, oxygen is transported in the blood by the _____.",
    ["red blood cells", "white blood cells", "platelets", "plasma proteins"], 0,
    "Haemoglobin in the red blood cells binds oxygen to form oxyhaemoglobin.", "easy"),
  q("SS2", 3, "Plant Transport", "Water and mineral salts are transported from the roots to the leaves through the _____.",
    ["xylem", "phloem", "cambium", "cortex"], 0,
    "The xylem carries water and dissolved minerals upward; the phloem translocates manufactured food.", "easy"),
  q("SS2", 3, "Ecology", "Organisms that feed on dead organic matter and return nutrients to the soil are called _____.",
    ["decomposers", "producers", "primary consumers", "carnivores"], 0,
    "Bacteria and fungi act as decomposers (saprophytes), breaking down dead remains.", "easy"),

  // ---------------- SS3 ----------------
  q("SS3", 1, "Genetics", "When two heterozygous tall plants (Tt \u00d7 Tt) are crossed, the phenotypic ratio of the offspring is _____.",
    ["3 tall : 1 short", "1 tall : 1 short", "all tall", "2 tall : 2 short"], 0,
    "Genotypes: 1 TT : 2 Tt : 1 tt. Since T is dominant, TT and Tt are tall - 3:1 phenotypic ratio.", "hard"),
  q("SS3", 1, "Cell Division", "The type of cell division that produces gametes with half the chromosome number is _____.",
    ["meiosis", "mitosis", "binary fission", "budding"], 0,
    "Meiosis is reduction division: diploid cells produce haploid gametes; mitosis conserves the chromosome number.", "easy"),
  q("SS3", 1, "Heredity", "The basic unit of inheritance is the _____.",
    ["gene", "chromosome", "nucleus", "allele pair"], 0,
    "A gene is a segment of DNA controlling a particular character; chromosomes simply carry many genes."),
  q("SS3", 2, "Variation", "Which of the following is an example of continuous variation in humans?",
    ["height", "blood group", "tongue rolling", "albinism"], 0,
    "Height shows a graded range of values (no distinct classes), unlike blood group which falls into discrete categories."),
  q("SS3", 2, "Evolution", "The theory of evolution by natural selection was proposed by _____.",
    ["Charles Darwin", "Jean Baptiste Lamarck", "Carolus Linnaeus", "Gregor Mendel"], 0,
    "Darwin (with Wallace) proposed that organisms with favourable variations survive and reproduce - natural selection."),
  q("SS3", 2, "Coordination", "The part of the mammalian brain responsible for balance and posture is the _____.",
    ["cerebellum", "cerebrum", "medulla oblongata", "hypothalamus"], 0,
    "The cerebellum coordinates muscular movement and maintains balance; the medulla controls involuntary actions.", "medium"),
  q("SS3", 3, "Hormones", "A deficiency of insulin in the body leads to _____.",
    ["diabetes mellitus", "goitre", "gigantism", "scurvy"], 0,
    "Insulin lowers blood glucose; its deficiency leaves blood sugar high - diabetes mellitus."),
  q("SS3", 3, "Nervous System", "In a reflex action, impulses travel from the receptor to the central nervous system through the _____.",
    ["sensory neurone", "motor neurone", "relay (intermediate) neurone only", "effector"], 0,
    "Reflex arc: receptor \u2192 sensory neurone \u2192 CNS (relay) \u2192 motor neurone \u2192 effector.", "hard"),
];
