import { q, SeedQ } from "./helpers";

export const chemistry: SeedQ[] = [
  // ---------------- SS1 ----------------
  q("SS1", 1, "Atomic Structure", "The atomic number of an element is the number of _____ in the nucleus of its atom.",
    ["protons", "neutrons", "electrons", "nucleons"], 0,
    "Atomic number Z = number of protons (which equals the number of electrons in a neutral atom).", "easy"),
  q("SS1", 1, "Atomic Structure", "Isotopes of the same element differ in the number of _____.",
    ["neutrons", "protons", "electrons", "valence shells"], 0,
    "Isotopes have the same proton number but different numbers of neutrons, hence different mass numbers.", "easy"),
  q("SS1", 1, "Electronic Configuration", "The electronic configuration of sodium (Na, atomic number 11) is _____.",
    ["2, 8, 1", "2, 8, 2", "2, 9", "8, 2, 1"], 0,
    "Sodium fills two electrons in the first shell, eight in the second, leaving one valence electron: 2,8,1.", "easy"),
  q("SS1", 2, "Periodic Table", "Elements in Group I of the periodic table are known as _____.",
    ["alkali metals", "halogens", "noble gases", "alkaline-earth metals"], 0,
    "Group I metals (Li, Na, K, ...) are the alkali metals - soft, reactive metals with one valence electron."),
  q("SS1", 2, "Chemical Symbols", "The chemical symbol Fe represents the element _____.",
    ["iron", "fluorine", "lead", "francium"], 0,
    "Fe comes from 'ferrum', the Latin name for iron.", "easy"),
  q("SS1", 3, "Separation Techniques", "An insoluble solid can best be separated from a liquid by _____.",
    ["filtration", "distillation", "sublimation", "chromatography"], 0,
    "Filtration traps the insoluble solid (residue) while the liquid passes through (filtrate).", "easy"),
  q("SS1", 3, "Separation Techniques", "Common salt is best recovered from its solution in water by _____.",
    ["evaporation", "filtration", "sieving", "magnetization"], 0,
    "The dissolved salt cannot be filtered; evaporating or crystallizing drives off the water to recover it."),
  q("SS1", 3, "Air", "The most abundant gas in the atmosphere is _____.",
    ["nitrogen", "oxygen", "carbon(IV) oxide", "argon"], 0,
    "Nitrogen makes up about 78% of the air; oxygen is about 21%.", "easy"),

  // ---------------- SS2 ----------------
  q("SS2", 1, "Stoichiometry", "How many moles are contained in 8 g of methane, CH\u2084? [C = 12, H = 1]",
    ["0.5 mol", "2 mol", "1 mol", "0.25 mol"], 0,
    "M(CH\u2084) = 12 + 4 = 16 g/mol. n = m/M = 8/16 = 0.5 mol."),
  q("SS2", 1, "Mole Concept", "The number of particles in one mole of a substance is _____.",
    ["6.02 \u00d7 10\u00b2\u00b3", "3.01 \u00d7 10\u00b2\u00b3", "6.02 \u00d7 10\u00b2\u00b2", "1.60 \u00d7 10\u207b\u00b9\u2079"], 0,
    "One mole contains Avogadro's number of particles: 6.02 \u00d7 10\u00b2\u00b3.", "easy"),
  q("SS2", 2, "Gas Laws", "Boyle's law states that at constant temperature, the volume of a fixed mass of gas is _____.",
    ["inversely proportional to its pressure", "directly proportional to its pressure", "independent of its pressure", "equal to its pressure"], 0,
    "Boyle's law: PV = constant; V \u221d 1/P at constant temperature.", "easy"),
  q("SS2", 2, "Gas Laws", "A gas occupies 2 dm\u00b3 at 300 kPa. At constant temperature, what pressure will compress it to 1 dm\u00b3?",
    ["600 kPa", "150 kPa", "300 kPa", "450 kPa"], 0,
    "P\u2081V\u2081 = P\u2082V\u2082 \u21d2 P\u2082 = (300 \u00d7 2)/1 = 600 kPa.", "medium"),
  q("SS2", 3, "Rate of Reaction", "Powdered calcium carbonate reacts faster with dilute hydrochloric acid than the lump form because the powder _____.",
    ["has a larger surface area", "is a stronger base", "contains more moles", "dissolves completely"], 0,
    "Grinding exposes more particles to the acid - a larger contact surface gives more frequent effective collisions."),
  q("SS2", 3, "Acids, Bases and Salts", "The pH of a solution that is 0.001 M hydrochloric acid is _____.",
    ["3", "11", "1", "7"], 0,
    "HCl is fully ionized: [H\u207a] = 10\u207b\u00b3 M, so pH = \u2212log(10\u207b\u00b3) = 3.", "hard"),
  q("SS2", 3, "Chemical Equilibrium", "A catalyst increases the rate of a chemical reaction by _____.",
    ["providing an alternative path of lower activation energy", "shifting the equilibrium to the right", "increasing the temperature of the reactants", "being used up in the reaction"], 0,
    "A catalyst lowers the activation energy and is recovered unchanged at the end of the reaction."),
  q("SS2", 3, "Indicators", "In an acidic solution, blue litmus paper turns _____.",
    ["red", "colourless", "green", "purple"], 0,
    "Acids turn blue litmus red; alkalis turn red litmus blue.", "easy"),

  // ---------------- SS3 ----------------
  q("SS3", 1, "Organic Chemistry", "The general molecular formula of the alkanes is _____.",
    ["C\u2099H\u2082\u2099\u208a\u2082", "C\u2099H\u2082\u2099", "C\u2099H\u2082\u2099\u208b\u2082", "C\u2099H\u2099"], 0,
    "Saturated hydrocarbons (alkanes) follow C\u2099H\u2082\u2099\u208a\u2082; alkenes follow C\u2099H\u2082\u2099.", "easy"),
  q("SS3", 1, "IUPAC Nomenclature", "The IUPAC name of the compound CH\u2083CH\u2082OH is _____.",
    ["ethanol", "methanol", "ethanal", "ethanoic acid"], 0,
    "Two carbons ('ethan-') plus the alkanol '-OH' group ('-ol') give ethanol.", "easy"),
  q("SS3", 1, "Homologous Series", "Successive members of a homologous series differ by _____.",
    ["CH\u2082", "CH\u2084", "CH", "C\u2082H\u2086"], 0,
    "Each member of a homologous series differs from the next by a -CH\u2082- unit (relative molecular mass of 14)."),
  q("SS3", 2, "Isomerism", "Compounds having the same molecular formula but different structural arrangements exhibit _____.",
    ["isomerism", "isotopy", "allotropy", "cracking"], 0,
    "Structural isomerism is the existence of compounds with the same molecular formula but different structures."),
  q("SS3", 2, "Functional Groups", "The functional group of the alkanols is _____.",
    ["-OH", "-COOH", "-CHO", "-NH\u2082"], 0,
    "Alkanols (alcohols) contain the hydroxyl group, -OH; -COOH is for alkanoic acids, -CHO for alkanals."),
  q("SS3", 2, "Petroleum and Polymerization", "Ethene undergoes addition polymerization to give _____.",
    ["polyethene", "polyvinyl chloride", "bakelite", "natural rubber"], 0,
    "Many ethene monomers join across the double bond to form polyethene (polythene)."),
  q("SS3", 3, "Electrolysis", "During electrolysis, cations migrate towards the _____.",
    ["cathode", "anode", "electrolyte surface", "salt bridge"], 0,
    "Cations are positively charged and are attracted to the negative electrode - the cathode.", "easy"),
  q("SS3", 3, "Electrolysis", "In the electrolysis of concentrated brine using inert electrodes, the gas liberated at the cathode is _____.",
    ["hydrogen", "chlorine", "oxygen", "hydrogen chloride"], 0,
    "Hydrogen is discharged at the cathode (lower discharge potential than Na\u207a); chlorine is freed at the anode.", "hard"),
  q("SS3", 3, "Redox Reactions", "Oxidation is defined as the _____.",
    ["loss of electrons", "gain of electrons", "gain of hydrogen", "removal of oxygen"], 0,
    "OILRIG: Oxidation Is Loss, Reduction Is Gain of electrons. (Oxidation also includes loss of hydrogen / gain of oxygen.)"),
  q("SS3", 3, "Thermochemistry", "For an exothermic reaction, the enthalpy change \u0394H is _____.",
    ["negative", "positive", "zero", "equal to the activation energy"], 0,
    "Heat is released to the surroundings, so the products have less energy than the reactants and \u0394H < 0."),
];
