import { q, SeedQ } from "./helpers";

export const civicEducation: SeedQ[] = [
  // ---------------- SS1 ----------------
  q("SS1", 1, "Introduction", "Civic education primarily focuses on the _____.",
    ["rights and responsibilities of citizens", "study of ancient buildings", "training of soldiers", "promotion of cultural festivals only"], 0,
    "Civic education equips citizens with knowledge of their rights, duties and the workings of government.", "easy", ["WAEC", "NECO"]),
  q("SS1", 1, "Values", "Societal values are best described as the _____.",
    ["cherished principles and standards that guide behaviour", "laws made by the national assembly", "punishments for crime", "goods sold in the market"], 0,
    "Values - honesty, integrity, fairness - are shared standards that shape conduct in a society.", "easy", ["WAEC", "NECO"]),
  q("SS1", 2, "Values", "The virtue of always telling the truth and being fair in dealings with others is _____.",
    ["honesty", "loyalty", "courage", "contentment"], 0,
    "Honesty combines truthfulness with fairness; it attracts trust and responsibility.", "easy", ["WAEC", "NECO"]),
  q("SS1", 2, "Human Rights", "The Universal Declaration of Human Rights (UDHR) was adopted by the United Nations in _____.",
    ["1948", "1945", "1960", "1999"], 0,
    "The UDHR was proclaimed by the UN General Assembly in Paris on 10 December 1948.", "medium", ["WAEC", "NECO"]),
  q("SS1", 3, "Rule of Law", "The rule of law means that _____.",
    ["everyone is equal before the law and the law is supreme", "lawyers rule the country", "the president is above the law", "courts exist in every town"], 0,
    "Under the rule of law, nobody - including leaders - is above the law, and all are equal before it.", "easy", ["WAEC", "NECO"]),
  q("SS1", 3, "Democracy", "Free and fair elections, rule of law and an independent judiciary are pillars of _____.",
    ["constitutional democracy", "military dictatorship", "feudalism", "colonialism"], 0,
    "These institutions protect the people's will - the essence of democratic governance.", "easy", ["WAEC", "NECO"]),

  // ---------------- SS2 ----------------
  q("SS2", 1, "Democracy", "Nigeria's official Democracy Day is celebrated every year on _____.",
    ["June 12", "October 1", "May 29", "January 15"], 0,
    "Since 2019, Democracy Day has been observed on June 12 in honour of the annulled 1993 election won by M. K. O. Abiola.", "medium", ["WAEC", "NECO"]),
  q("SS2", 1, "Human Rights", "Which of the following is an example of a fundamental human right?",
    ["right to life", "right to own a car", "right to free petrol", "right to vote at any age"], 0,
    "The right to life, dignity, personal liberty and fair hearing are fundamental rights in Chapter IV of the 1999 Constitution.", "easy", ["WAEC", "NECO"]),
  q("SS2", 2, "Anti-corruption Agencies", "The Economic and Financial Crimes Commission (EFCC) was established in _____.",
    ["2003", "2000", "1999", "2010"], 0,
    "The EFCC was set up in 2003 to fight economic and financial crimes such as fraud and money laundering.", "medium", ["WAEC", "NECO"]),
  q("SS2", 2, "Regulatory Agencies", "The agency responsible for regulating food and drug standards in Nigeria is _____.",
    ["NAFDAC", "SON", "NDLEA", "NAFDEC"], 0,
    "The National Agency for Food and Drug Administration and Control (NAFDAC) guards against fake and substandard products.", "easy", ["WAEC", "NECO"]),
  q("SS2", 3, "Traffic Regulation", "The Federal Road Safety Corps (FRSC) was established in _____.",
    ["1988", "1978", "1998", "2003"], 0,
    "The FRSC was created in 1988 to make Nigerian highways safe and to check road traffic crashes.", "medium", ["WAEC", "NECO"]),
  q("SS2", 3, "Law Enforcement", "The body charged with fighting the production and trafficking of hard drugs in Nigeria is the _____.",
    ["NDLEA", "NSCDC", "EFCC", "ICPC"], 0,
    "The National Drug Law Enforcement Agency targets drug barons and trafficking networks.", "easy", ["WAEC", "NECO"]),

  // ---------------- SS3 ----------------
  q("SS3", 1, "HIV/AIDS", "The full meaning of HIV is _____.",
    ["Human Immunodeficiency Virus", "High Immunity Virus", "Human Internal Virus", "Health Infection Virus"], 0,
    "HIV - the Human Immunodeficiency Virus - attacks the immune system and can lead to AIDS if untreated.", "easy", ["WAEC", "NECO"]),
  q("SS3", 1, "HIV/AIDS", "HIV can be transmitted through all of the following EXCEPT _____.",
    ["hugging and shaking hands", "unscreened blood transfusion", "sharing of sharp objects", "unprotected sexual intercourse"], 0,
    "HIV is NOT spread by casual contact such as hugging, handshakes or sharing plates.", "easy", ["WAEC", "NECO"]),
  q("SS3", 2, "Separation of Powers", "The doctrine of separation of powers was popularised by _____.",
    ["Baron de Montesquieu", "Abraham Lincoln", "John Locke alone", "Karl Marx"], 0,
    "In 'The Spirit of Laws' (1748), Montesquieu argued that liberty is safest when executive, legislative and judicial powers are held separately.", "medium", ["WAEC", "NECO"]),
  q("SS3", 2, "Constitution", "The constitution currently in operation in Nigeria is the _____.",
    ["1999 Constitution", "1989 Constitution", "1979 Constitution", "1963 Constitution"], 0,
    "Nigeria returned to civil rule on 29 May 1999 under the 1999 Constitution (as amended).", "easy", ["WAEC", "NECO"]),
  q("SS3", 3, "Citizenship", "One important duty of a citizen to the state is _____.",
    ["payment of taxes", "joining a secret cult", "forgetting the national anthem", "avoiding census exercises"], 0,
    "Duties of citizens include paying taxes, obeying laws, voting and defending the nation.", "easy", ["WAEC", "NECO"]),
  q("SS3", 3, "National Consciousness", "The green colour in the Nigerian national flag represents _____.",
    ["agriculture and natural wealth", "peace and unity", "the rivers of the nation", "strength of the armed forces"], 0,
    "The white band stands for peace; the two green bands represent agriculture and the country's natural wealth.", "easy", ["WAEC", "NECO"]),
];
