import { q, SeedQ } from "./helpers";

export const economics: SeedQ[] = [
  // ---------------- SS1 ----------------
  q("SS1", 1, "Basic Concepts", "Economics is best defined as the study of how society _____.",
    ["allocates its scarce resources among competing wants", "prints and distributes money", "trains people for political office", "records the history of trade"], 0,
    "The core of economics is scarcity: unlimited wants against limited resources, forcing choice.", "easy"),
  q("SS1", 1, "Opportunity Cost", "The opportunity cost of a choice is _____.",
    ["the next best alternative forgone", "the money price paid for the item", "the total of all alternatives given up", "the benefit enjoyed from the choice"], 0,
    "Opportunity cost is the single best alternative sacrificed, not the money spent.", "easy"),
  q("SS1", 1, "Factors of Production", "The reward for labour as a factor of production is _____.",
    ["wages", "rent", "interest", "profit"], 0,
    "Land earns rent, labour earns wages, capital earns interest, and the entrepreneur earns profit.", "easy"),
  q("SS1", 2, "Scale of Preference", "A scale of preference is important because it _____.",
    ["helps an individual rank wants and make rational choices", "increases the income of the consumer", "removes the problem of scarcity", "lists goods according to size"], 0,
    "By ranking wants in order of importance, a scale of preference guides choice under scarcity."),
  q("SS1", 2, "Basic Economic Problems", "The fundamental economic problem facing all societies is _____.",
    ["scarcity", "inflation", "poverty", "unemployment"], 0,
    "Scarcity forces every economy to answer what to produce, how to produce, and for whom to produce."),
  q("SS1", 3, "Demand", "Other things being equal, when the price of a commodity rises, the quantity demanded _____.",
    ["falls", "rises", "remains constant", "falls to zero"], 0,
    "The law of demand describes an inverse relationship between price and quantity demanded.", "easy"),
  q("SS1", 3, "Markets", "A market is best described as any arrangement where _____.",
    ["buyers and sellers are brought into contact to exchange goods and services", "only farm produce is sold", "fixed prices are set by government", "goods are produced"], 0,
    "A market needs buyers, sellers and a means of contact - it may be physical or virtual."),

  // ---------------- SS2 ----------------
  q("SS2", 1, "Utility", "Utility in economics means the _____.",
    ["satisfaction derived from consuming a commodity", "usefulness of money in the bank", "price of a good in the market", "scarcity of a resource"], 0,
    "Utility is the satisfaction a consumer obtains; it is subjective and differs from person to person."),
  q("SS2", 1, "Elasticity", "Price elasticity of demand is measured as _____.",
    ["% change in quantity demanded \u00f7 % change in price", "% change in price \u00f7 % change in quantity demanded", "change in price \u00d7 change in quantity", "% change in income \u00f7 % change in demand"], 0,
    "PED = \u0394Qd% / \u0394P%. Values above 1 are elastic; below 1 are inelastic.", "hard"),
  q("SS2", 2, "Market Structures", "A market structure with many buyers and sellers dealing in an identical product is _____.",
    ["perfect competition", "monopoly", "oligopoly", "monopsony"], 0,
    "Perfect competition has many buyers and sellers, a homogeneous product and no barrier to entry."),
  q("SS2", 2, "Market Structures", "A market in which there is only one seller of a commodity is called _____.",
    ["a monopoly", "an oligopoly", "perfect competition", "a duopoly"], 0,
    "A single seller with no close substitutes defines a monopoly.", "easy"),
  q("SS2", 3, "Money", "Which of the following is a function of money?",
    ["medium of exchange", "barter facilitation", "creation of scarcity", "price fixing"], 0,
    "Money serves as a medium of exchange, a unit of account, a store of value and a standard for deferred payment.", "easy"),
  q("SS2", 3, "Inflation", "Inflation is defined as a persistent rise in the _____.", 
    ["general price level", "price of one commodity", "level of employment", "value of money"], 0,
    "Inflation is a sustained increase in the average (general) level of prices, which reduces the purchasing power of money."),

  // ---------------- SS3 ----------------
  q("SS3", 1, "National Income", "The Gross Domestic Product (GDP) of a country is the total value of goods and services produced _____.",
    ["within the country's borders in a given period", "by its citizens abroad in a year", "by the public sector only", "for export alone"], 0,
    "GDP counts output produced within the geographical boundaries; GNP counts output by nationals wherever they are."),
  q("SS3", 1, "Population", "The optimum population of a country is the population size that, combined with available resources, yields the _____.",
    ["maximum output per head", "fastest population growth", "largest land area per person", "highest number of births"], 0,
    "At optimum population, output per capita is at its highest given existing resources and technology.", "hard"),
  q("SS3", 2, "Money and Banking", "The Central Bank of Nigeria commenced operations in _____.",
    ["1959", "1960", "1958", "1963"], 0,
    "The CBN was established by the 1958 Act and began operations on 1 July 1959 - a classic JAMB fact.", "hard"),
  q("SS3", 3, "International Trade", "The theory of comparative advantage in international trade is associated with _____.",
    ["David Ricardo", "Adam Smith", "J. M. Keynes", "Thomas Malthus"], 0,
    "Ricardo showed countries gain by specialising where their relative (comparative) cost advantage is greatest."),
  q("SS3", 3, "Economic Organizations", "The Economic Community of West African States (ECOWAS) was established in _____.",
    ["1975", "1963", "1980", "1991"], 0,
    "ECOWAS was founded by the Lagos Treaty of 28 May 1975 to promote regional economic cooperation."),
];
