import { q, SeedQ } from "./helpers";

export const english: SeedQ[] = [
  // ---------------- SS1 ----------------
  q("SS1", 1, "Synonyms", "Choose the option nearest in meaning to the capitalised word: The witness gave a CANDID account of the event.",
    ["frank", "confusing", "brief", "false"], 0,
    "'Candid' means truthful and straightforward; 'frank' is its nearest synonym.", "easy"),
  q("SS1", 1, "Antonyms", "Choose the option opposite in meaning to the capitalised word: Food was SCARCE during the drought.",
    ["abundant", "cheap", "stale", "costly"], 0,
    "The opposite of 'scarce' is 'abundant' - existing in large quantities.", "easy"),
  q("SS1", 1, "Concord", "Neither the boys nor the girl _____ here yesterday.",
    ["was", "were", "are", "have been"], 0,
    "With 'neither...nor', the verb agrees with the nearer subject - 'the girl' - so it takes 'was'.", "hard"),
  q("SS1", 2, "Question Tags", "You will come to the party, _____?",
    ["won't you", "will you", "wouldn't you", "shan't you"], 0,
    "A positive statement takes a negative tag of the same auxiliary: 'will' becomes 'won't you'.", "easy"),
  q("SS1", 2, "Active and Passive Voice", "Choose the correct passive form of: 'The teacher praised the boy.'",
    ["The boy was praised by the teacher.", "The boy was being praised by the teacher.", "The boy is praised by the teacher.", "The boy had been praised by the teacher."], 0,
    "Simple past active 'praised' becomes simple past passive 'was praised'."),
  q("SS1", 2, "Prepositions", "The doctor advised him to abstain _____ smoking.",
    ["from", "for", "with", "against"], 0,
    "The verb 'abstain' is followed by the preposition 'from'.", "easy"),
  q("SS1", 3, "Idioms", "'The duo decided to bury the hatchet' means they decided to _____.",
    ["make peace", "hide a weapon", "start afresh secretly", "hold a meeting"], 0,
    "To 'bury the hatchet' is an idiom meaning to end a quarrel and make peace."),
  q("SS1", 3, "Vocabulary", "Which of the following words has the same vowel sound as 'food' /u\u02d0/?",
    ["mood", "blood", "flood", "good"], 0,
    "'Mood' has the long /u\u02d0/ sound of 'food'; 'blood' and 'flood' take /\u028c/, and 'good' takes the short /\u028a/.", "hard"),

  // ---------------- SS2 ----------------
  q("SS2", 1, "Synonyms", "Choose the option nearest in meaning to the capitalised word: The BENEVOLENT woman donated her fortune to the school.",
    ["kind", "wealthy", "gentle", "popular"], 0,
    "'Benevolent' means well-meaning and kindly disposed; 'kind' is nearest in meaning."),
  q("SS2", 1, "Concord", "The news broadcast on television last night _____ very encouraging.",
    ["was", "were", "is", "have been"], 0,
    "'News' is an uncountable noun and always takes a singular verb; 'last night' fixes the tense as past.", "hard"),
  q("SS2", 2, "Idioms", "In the sentence, 'The allegation about bribes was a red herring', the paragraph means the allegation was _____.",
    ["a distraction", "a serious offence", "eventually proved", "widespread"], 0,
    "A 'red herring' is something that diverts attention from the real issue - a distraction."),
  q("SS2", 2, "Reported Speech", "Choose the correct reported form: He said, 'I am tired.'",
    ["He said that he was tired.", "He said that he is tired.", "He said that I was tired.", "He said that he had been tired."], 0,
    "In reported speech the present tense shifts back: 'am' becomes 'was', and 'I' becomes 'he'."),
  q("SS2", 2, "Lexis and Structure", "The carpenter used a _____ to make the surface of the wood smooth.",
    ["plane", "chisel", "mallet", "brace"], 0,
    "A plane is the carpenter's tool for smoothing wooden surfaces; a chisel cuts, a mallet strikes."),
  q("SS2", 3, "Figures of Speech", "'The argument was as clear as crystal' is an example of _____.",
    ["simile", "metaphor", "personification", "hyperbole"], 0,
    "The comparison uses 'as...as', the marker of a simile.", "easy"),
  q("SS2", 3, "Figures of Speech", "'The wind whispered through the trees' illustrates _____.",
    ["personification", "simile", "irony", "metonymy"], 0,
    "The wind is given the human quality of whispering - that is personification.", "easy"),
  q("SS2", 3, "Stress and Emphasis", "In 'JOHN bought a car', where the capitalised word is emphasised, the sentence answers the question _____.",
    ["Who bought a car?", "What did John buy?", "Did John buy a car?", "Whose car did John buy?"], 0,
    "Emphatic stress on the subject signals that the question concerns the doer of the action."),

  // ---------------- SS3 ----------------
  q("SS3", 1, "Synonyms", "Choose the option nearest in meaning to the capitalised word: The accountant was METICULOUS in keeping the records.",
    ["very careful", "very slow", "quite lazy", "somewhat clever"], 0,
    "'Meticulous' means showing great attention to detail - very careful.", "medium"),
  q("SS3", 1, "Antonyms", "Choose the option opposite in meaning to the capitalised word: His interest in the project was only TRANSIENT.",
    ["permanent", "genuine", "slight", "strong"], 0,
    "'Transient' means lasting only a short time; its opposite is 'permanent'."),
  q("SS3", 1, "Concord", "Each and every one of us _____ guilty of the offence.",
    ["is", "are", "were", "have been"], 0,
    "'Each and every one' is singular and takes a singular verb - 'is'.", "hard"),
  q("SS3", 2, "Idioms", "'The disgraced official was told to face the music' means he was told to _____.",
    ["accept the consequences of his actions", "attend a concert as punishment", "confess before a panel", "resign immediately"], 0,
    "To 'face the music' is to accept the unpleasant consequences of one's own actions."),
  q("SS3", 2, "Phrasal Verbs", "The meeting was called _____ because of the student's unrest.",
    ["off", "on", "up", "out"], 0,
    "To 'call off' a meeting is to cancel it.", "easy"),
  q("SS3", 2, "Idioms", "The phrase 'at sixes and sevens' means _____.",
    ["in a state of confusion", "in correct numerical order", "perfectly arranged", "scattered abroad"], 0,
    "To be 'at sixes and sevens' is to be in confusion or disarray."),
  q("SS3", 3, "Lexis and Structure", "The list of candidates _____ of ten names.",
    ["consists", "consist", "is consisting", "are consisting"], 0,
    "'Consist' is a stative verb (no continuous form) and 'the list' is singular, so 'consists' is correct.", "hard"),
  q("SS3", 3, "Synonyms", "Choose the option nearest in meaning to the capitalised word in: 'His FRIVOLOUS remarks annoyed the principal.'",
    ["not serious", "rare", "offensive", "lengthy"], 0,
    "'Frivolous' means lacking seriousness or sense - 'not serious'.", "medium"),
];
