import { q, SeedQ } from "./helpers";

export const government: SeedQ[] = [
  // ---------------- SS1 ----------------
  q("SS1", 1, "Arms of Government", "The arm of government responsible for implementing laws is the _____.",
    ["executive", "legislature", "judiciary", "civil service only"], 0,
    "The executive implements and enforces laws; the legislature makes them and the judiciary interprets them.", "easy"),
  q("SS1", 1, "Democracy", "'Government of the people, by the people and for the people' is the definition of democracy given by _____.",
    ["Abraham Lincoln", "Karl Marx", "Baron de Montesquieu", "John Locke"], 0,
    "The famous Gettysburg definition of democracy came from American President Abraham Lincoln.", "easy"),
  q("SS1", 1, "Arms of Government", "The primary function of the legislature in a modern state is to _____.",
    ["make laws", "punish offenders", "command the armed forces", "appoint judges"], 0,
    "Law-making is the legislature's core function, alongside representation and oversight of the executive.", "easy"),
  q("SS1", 2, "Constitution", "A constitution is described as rigid when it _____.",
    ["is very difficult to amend", "cannot be interpreted by the courts", "is not written down", "has only a few articles"], 0,
    "A rigid constitution requires a special, difficult procedure for amendment, unlike a flexible one."),
  q("SS1", 2, "Constitution", "A classic example of a country operating an unwritten constitution is _____.",
    ["Britain", "the United States", "Nigeria", "France"], 0,
    "Britain's constitution is uncodified - drawn from statutes, conventions and case law.", "medium"),
  q("SS1", 3, "Citizenship", "A person who owes allegiance to a state and is entitled to its protection is a _____.",
    ["citizen", "resident", "refugee", "diplomat"], 0,
    "Citizenship is the legal bond of allegiance between a person and a state, with reciprocal rights and duties.", "easy"),
  q("SS1", 3, "Franchise", "The right of qualified adults to vote in an election is called _____.",
    ["franchise", "referendum", "plebiscite right", "mandate"], 0,
    "Franchise (suffrage) is the right to vote; universal adult suffrage extends it to all qualified adults.", "easy"),

  // ---------------- SS2 ----------------
  q("SS2", 1, "Colonial Administration", "Indirect rule in Northern Nigeria was introduced by _____.",
    ["Lord Frederick Lugard", "Sir Hugh Clifford", "Lord Lugard's successor Bernard Bourdillon", "Sir Donald Cameron"], 0,
    "Lugard administered Northern Nigeria through the emirs - the hallmark of indirect rule."),
  q("SS2", 1, "Pre-colonial Administration", "The traditional political system of the Igbo of pre-colonial Nigeria is best described as _____.",
    ["acephalous (stateless)", "highly centralized", "a Muslim theocracy", "an absolute monarchy"], 0,
    "Igbo villages ruled through councils of elders and age grades, without a single paramount ruler - a segmentary (acephalous) system."),
  q("SS2", 2, "Nationalism", "The first political party in Nigeria, founded in 1923, was the _____.",
    ["Nigerian National Democratic Party", "National Council of Nigerian Citizens", "Action Group", "Northern People's Congress"], 0,
    "Herbert Macaulay founded the NNDP in 1923 following the Clifford Constitution of 1922."),
  q("SS2", 2, "Nationalism", "The National Council of Nigeria and the Cameroons (NCNC) was formed in _____.",
    ["1944", "1922", "1951", "1960"], 0,
    "The NCNC was formed in 1944 with Herbert Macaulay as first president and Nnamdi Azikiwe as secretary."),
  q("SS2", 3, "Constitutional Development", "Nigeria became a republic in _____.",
    ["1963", "1960", "1966", "1979"], 0,
    "The 1963 Republican Constitution replaced the Queen with a Nigerian President; Dr Nnamdi Azikiwe became the first President.", "easy"),
  q("SS2", 3, "Constitutional Development", "The first indigenous Governor-General of Nigeria was _____.",
    ["Nnamdi Azikiwe", "Tafawa Balewa", "Obafemi Awolowo", "Ahmadu Bello"], 0,
    "Azikiwe served as Nigeria's first indigenous Governor-General from 1960 before becoming President in 1963."),

  // ---------------- SS3 ----------------
  q("SS3", 1, "Federalism", "The 1979 Constitution of Nigeria introduced the _____.",
    ["presidential system of government", "parliamentary system", "confederal system", "unitary system"], 0,
    "The 1979 Constitution adopted the American-style executive presidency, replacing the First Republic's Westminster model."),
  q("SS3", 1, "Federalism", "The federal character principle in Nigeria is designed to _____.",
    ["ensure fair representation of all states and groups in public appointments", "make one region dominate the civil service", "abolish quota system in education", "centralize revenue sharing"], 0,
    "Federal character guarantees that ministries, agencies and appointments reflect Nigeria's diversity."),
  q("SS3", 2, "Military Rule", "The first military coup in Nigeria took place in _____.",
    ["January 1966", "July 1966", "October 1963", "July 1975"], 0,
    "The coup of 15 January 1966, led by Major Nzeogwu and others, ended the First Republic."),
  q("SS3", 2, "Electoral Bodies", "The Independent National Electoral Commission (INEC) was established in _____.",
    ["1998", "1978", "1987", "1999"], 0,
    "General Abubakar's transition programme created INEC in 1998 to conduct the 1999 elections.", "hard"),
  q("SS3", 3, "International Organizations", "The United Nations Organization (UNO) was founded in _____.",
    ["1945", "1919", "1939", "1950"], 0,
    "The UN Charter was signed in San Francisco in June 1945, replacing the League of Nations.", "easy"),
  q("SS3", 3, "International Organizations", "The Organization of African Unity (OAU) was transformed into the African Union in _____.",
    ["2002", "2000", "1963", "1999"], 0,
    "The AU was officially launched in Durban, South Africa, in July 2002, succeeding the OAU founded in 1963."),
];
