import { q, SeedQ } from "./helpers";

export const literature: SeedQ[] = [
  // ---------------- SS1 ----------------
  q("SS1", 1, "Genres", "The three main genres of literature are _____.",
    ["prose, poetry and drama", "fiction, non-fiction and folklore", "novel, play and essay", "tragedy, comedy and farce"], 0,
    "Literature is conventionally divided into prose, poetry and drama; the other options are sub-forms.", "easy"),
  q("SS1", 1, "Poetry Terms", "A long narrative poem that celebrates the heroic deeds of a legendary figure is _____.",
    ["an epic", "an ode", "a ballad", "a limerick"], 0,
    "The epic recounts heroic adventures on a grand scale (e.g. the Epic of Sundiata); a ballad tells shorter folk stories."),
  q("SS1", 2, "Figures of Speech", "'The classroom was a zoo during the break' is an example of _____.",
    ["metaphor", "simile", "personification", "alliteration"], 0,
    "The classroom is directly called a zoo - a direct comparison without 'like' or 'as' - a metaphor.", "easy"),
  q("SS1", 2, "Sound Devices", "The repetition of the same initial consonant sound in neighbouring words, as in 'Peter Piper picked...', is called _____.",
    ["alliteration", "assonance", "onomatopoeia", "rhyme"], 0,
    "Alliteration repeats initial consonant sounds; assonance repeats vowel sounds within words.", "easy"),
  q("SS1", 3, "Poetry Terms", "A group of lines forming a unit in a poem is a _____.",
    ["stanza", "canto line", "refrain", "foot"], 0,
    "A stanza is the 'verse paragraph' of a poem, set off by a space; a refrain is a repeated line.", "easy"),
  q("SS1", 3, "Prose Terms", "A short story in which animals speak and act like humans to teach a moral lesson is _____.",
    ["a fable", "an epic", "a memoir", "a legend"], 0,
    "Fables such as the tortoise tales use animal characters to embody human foibles and end with a moral.", "easy"),

  // ---------------- SS2 ----------------
  q("SS2", 1, "Figures of Speech", "'I have told you a million times to lock the door' illustrates _____.",
    ["hyperbole", "irony", "euphemism", "litotes"], 0,
    "'A million times' is deliberate exaggeration for emphasis - hyperbole.", "easy"),
  q("SS2", 1, "Sound Devices", "The use of words whose sounds suggest their meaning, such as 'buzz' and 'hiss', is _____.",
    ["onomatopoeia", "alliteration", "assonance", "pun"], 0,
    "Onomatopoeia imitates natural sounds in words.", "easy"),
  q("SS2", 2, "Poetry Types", "A poem of fourteen lines, usually in iambic pentameter, is _____.",
    ["a sonnet", "an ode", "an elegy", "an epic"], 0,
    "The sonnet (Petrarchan or Shakespearean) contains exactly fourteen lines.", "easy"),
  q("SS2", 2, "Poetry Types", "A poem written to mourn the dead is _____.",
    ["an elegy", "an ode", "a ballad", "a pastoral"], 0,
    "An elegy laments a death, whereas an ode addresses or celebrates its subject.", "easy"),
  q("SS2", 2, "Prose Terms", "A narrator who knows the thoughts and feelings of every character in a story is _____.",
    ["an omniscient narrator", "a first-person narrator", "an unreliable narrator", "a participant narrator"], 0,
    "The omniscient ('all-knowing') narrator sees into every character's mind; the first-person narrator is limited to 'I'."),
  q("SS2", 3, "Drama", "A play which ends in the downfall or death of the hero, moving the audience to pity and fear, is _____.",
    ["a tragedy", "a comedy", "a farce", "a melodrama"], 0,
    "Tragedy depicts the fall of a noble protagonist; comedy ends happily, often in marriage or reconciliation.", "easy"),
  q("SS2", 3, "Drama", "When the audience knows more about events than the characters on stage, the effect is called _____.",
    ["dramatic irony", "suspense", "comic relief", "foreshadowing"], 0,
    "Dramatic irony exploits the gap between what the audience knows and what the characters know.", "hard"),

  // ---------------- SS3 ----------------
  q("SS3", 1, "Dramatic Techniques", "A speech in which a character, alone on stage, reveals his inner thoughts to the audience is _____.",
    ["a soliloquy", "an aside", "a monologue to another character", "a prologue"], 0,
    "In a soliloquy the character thinks aloud alone; an aside is a brief remark others on stage do not hear.", "hard"),
  q("SS3", 1, "Dramatic Techniques", "A remark made by a character which is heard by the audience but not by the other characters on stage is _____.",
    ["an aside", "a soliloquy", "a chorus", "an epilogue"], 0,
    "The aside breaks the dramatic illusion briefly so the audience alone shares a secret.", "hard"),
  q("SS3", 2, "Narrative Techniques", "An interruption of a narrative to present events that happened earlier is known as _____.",
    ["flashback", "foreshadowing", "climax", "denouement"], 0,
    "Flashback (analepsis) rewinds the story to a past event; foreshadowing hints at what is to come."),
  q("SS3", 2, "Tone and Mood", "The overall emotional atmosphere a literary work creates in the reader is its _____.",
    ["mood", "tone", "theme", "setting"], 0,
    "Mood is what the reader feels; tone is the writer's attitude towards the subject. The two are frequently confused in exams.", "hard"),
  q("SS3", 3, "Fatal Flaw", "The weakness of character which brings about the downfall of a tragic hero is called _____.",
    ["hamartia", "hubris alone", "catharsis", "nemesis"], 0,
    "Hamartia is the tragic flaw or error of judgement in Aristotle's account of tragedy.", "hard"),
  q("SS3", 3, "Poetry Forms", "Verse written in unrhymed iambic pentameter is described as _____.",
    ["blank verse", "free verse", "heroic couplet", "prose poetry"], 0,
    "Blank verse keeps the iambic pentameter rhythm but drops rhyme - the medium of much Shakespearean drama.", "hard"),
  q("SS3", 3, "Plot", "The unravelling or resolution of the complications of a plot at the end of a play or novel is the _____.",
    ["denouement", "climax", "exposition", "anti-climax"], 0,
    "The denouement unties the knot of the plot after the climax; exposition introduces it."),
];
