import { q, SeedQ } from "./helpers";

export const physics: SeedQ[] = [
  // ---------------- SS1 ----------------
  q("SS1", 1, "Fundamental Quantities", "Which of the following is a fundamental quantity?",
    ["mass", "velocity", "force", "energy"], 0,
    "Mass, length, time, temperature, electric current, amount of substance and luminous intensity are fundamental; velocity, force and energy are derived.", "easy"),
  q("SS1", 1, "Units", "The SI unit of force is the _____.",
    ["newton", "joule", "watt", "pascal"], 0,
    "Force (mass \u00d7 acceleration, kg m/s\u00b2) is measured in newtons.", "easy"),
  q("SS1", 1, "Scalars and Vectors", "Which of the following is a vector quantity?",
    ["velocity", "speed", "mass", "temperature"], 0,
    "A vector has both magnitude and direction. Velocity is directed speed; the others have magnitude only.", "easy"),
  q("SS1", 2, "Motion", "A body starts from rest and accelerates uniformly at 2 m/s\u00b2 for 5 s. Its final velocity is _____.",
    ["10 m/s", "7 m/s", "2.5 m/s", "25 m/s"], 0,
    "v = u + at = 0 + 2 \u00d7 5 = 10 m/s.", "medium"),
  q("SS1", 2, "Elasticity", "A spring of force constant 100 N/m is stretched by 0.03 m. Calculate the applied force.",
    ["3 N", "30 N", "0.3 N", "300 N"], 0,
    "By Hooke's law, F = ke = 100 \u00d7 0.03 = 3 N."),
  q("SS1", 2, "Density", "A block has a mass of 200 g and a volume of 50 cm\u00b3. Its density is _____.",
    ["4 g/cm\u00b3", "0.25 g/cm\u00b3", "250 g/cm\u00b3", "40 g/cm\u00b3"], 0,
    "Density = mass/volume = 200/50 = 4 g/cm\u00b3.", "easy"),
  q("SS1", 3, "Work and Energy", "Calculate the kinetic energy of a body of mass 2 kg moving with a velocity of 3 m/s.",
    ["9 J", "6 J", "12 J", "18 J"], 0,
    "KE = \u00bdmv\u00b2 = \u00bd \u00d7 2 \u00d7 3\u00b2 = 9 J."),
  q("SS1", 3, "Heat Energy", "The SI unit of specific heat capacity is _____.",
    ["J kg\u207b\u00b9 K\u207b\u00b9", "J kg\u207b\u00b9", "J K\u207b\u00b9", "W m\u207b\u00b9 K\u207b\u00b9"], 0,
    "From Q = mc\u0394\u03b8, c = Q/(m\u0394\u03b8), giving joules per kilogram per kelvin: J kg\u207b\u00b9 K\u207b\u00b9.", "hard"),

  // ---------------- SS2 ----------------
  q("SS2", 1, "Waves", "A wave has a frequency of 50 Hz and a wavelength of 4 m. Its velocity is _____.",
    ["200 m/s", "12.5 m/s", "54 m/s", "0.08 m/s"], 0,
    "v = f\u03bb = 50 \u00d7 4 = 200 m/s.", "easy"),
  q("SS2", 1, "Waves", "Which of the following is a longitudinal wave?",
    ["sound wave", "light wave", "water ripple", "radio wave"], 0,
    "In a longitudinal wave the particles vibrate parallel to the direction of travel - the case for sound. Light, ripples and radio waves are transverse."),
  q("SS2", 1, "Waves", "The period of a wave of frequency 25 Hz is _____.",
    ["0.04 s", "25 s", "4 s", "0.4 s"], 0,
    "T = 1/f = 1/25 = 0.04 s.", "easy"),
  q("SS2", 2, "Light", "The image formed by a plane mirror is always _____.",
    ["virtual and upright", "real and inverted", "virtual and magnified", "real and diminished"], 0,
    "A plane mirror gives a virtual, upright, laterally inverted image the same size as the object.", "easy"),
  q("SS2", 2, "Refraction", "When a ray of light passes from air into water, it bends _____.",
    ["towards the normal", "away from the normal", "along the normal", "away from the water surface"], 0,
    "Water is optically denser than air, so the ray slows down and bends towards the normal."),
  q("SS2", 3, "Current Electricity", "A potential difference of 6 V is applied across a 3 \u03a9 resistor. The current flowing is _____.",
    ["2 A", "0.5 A", "18 A", "9 A"], 0,
    "By Ohm's law, I = V/R = 6/3 = 2 A.", "easy"),
  q("SS2", 3, "Resistors", "Two resistors of 2 \u03a9 each are connected in parallel. Their effective resistance is _____.",
    ["1 \u03a9", "4 \u03a9", "2 \u03a9", "0.5 \u03a9"], 0,
    "1/R = 1/2 + 1/2 = 1, so R = 1 \u03a9. Equal resistors in parallel: R/n = 2/2 = 1 \u03a9."),
  q("SS2", 3, "Electric Circuits", "The instrument used for measuring electric current is the _____.",
    ["ammeter", "voltmeter", "galvanoscope", "ohmmeter"], 0,
    "Current is measured with an ammeter connected in series; a voltmeter measures potential difference.", "easy"),

  // ---------------- SS3 ----------------
  q("SS3", 1, "Gravitational Field", "According to Newton's law of universal gravitation, the force between two masses is inversely proportional to _____.",
    ["the square of the distance between them", "the distance between them", "the sum of the masses", "the product of the masses"], 0,
    "F = Gm\u2081m\u2082/r\u00b2 - the force varies inversely with the square of the separation."),
  q("SS3", 2, "Capacitors", "A capacitor stores a charge of 10 \u03bcC when connected across a 5 V battery. Its capacitance is _____.",
    ["2 \u03bcF", "50 \u03bcF", "0.5 \u03bcF", "15 \u03bcF"], 0,
    "C = Q/V = 10/5 = 2 \u03bcF."),
  q("SS3", 2, "Electromagnetism", "Fleming's left-hand rule is used to determine the direction of _____.",
    ["the force on a current-carrying conductor in a magnetic field", "the induced current in a generator", "the magnetic field around a wire", "the flux through a coil"], 0,
    "The left-hand (motor) rule gives the direction of the force (motion); the right-hand rule handles induced currents.", "hard"),
  q("SS3", 3, "Modern Physics", "The photoelectric effect provides evidence that light behaves as _____.",
    ["particles", "waves", "a magnetic field", "an electrolyte"], 0,
    "The emission of electrons depends on frequency, not intensity - evidence that light energy arrives in packets (photons)."),
  q("SS3", 3, "Radioactivity", "A radioactive sample of 80 g has a half-life of 4 days. What mass remains after 8 days?",
    ["20 g", "10 g", "40 g", "5 g"], 0,
    "8 days = 2 half-lives: 80 \u2192 40 \u2192 20 g.", "medium"),
  q("SS3", 3, "Electronics", "Doping a pure semiconductor with a pentavalent impurity produces _____.",
    ["an n-type semiconductor", "a p-type semiconductor", "an insulator", "a superconductor"], 0,
    "Pentavalent (donor) atoms add free electrons as majority carriers, giving an n-type material.", "hard"),
];
