#!/usr/bin/env python3
"""
MAMSS Prep — school activation code issuer (v45 "Roll Call").

Creates a batch of branded, single-use activation codes and publishes ONLY the
salted SHA-256 hashes to docs/codes.js (the public half). The plaintext list is
written to tools/private/ — which is git-ignored and must never be committed,
uploaded, or pasted anywhere.

    python3 tools/issue_codes.py --count 120            # first batch
    python3 tools/issue_codes.py --count 40 --batch SS2-intake   # top up later

Code shape:  MAMSS-7K4Q2R-2026   (brand · 6 unambiguous chars · year)
Normalised for hashing/entry: alphanumerics only, upper-case, so
"MAMSS-7K4Q2R-2026", "mamss 7k4q2r 2026" and "MAMSS7K4Q2R2026" all work.

Safety rails built in:
  • refuses to run unless tools/private/ is git-ignored (and adds it if missing)
  • never re-issues a code that already exists in docs/codes.js
  • appends to the existing salt/hash list so old codes keep working
  • prints how many codes exist afterwards, so you can sanity-check the batch
"""
import argparse
import csv
import datetime as dt
import hashlib
import html
import os
import re
import secrets
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
PRIVATE = os.path.join(ROOT, "tools", "private")
CODES_JS = os.path.join(DOCS, "codes.js")

ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"      # no 0/O, 1/I/L — safe on a whiteboard
YEAR = str(dt.date.today().year)


def normalize(code: str) -> str:
    return re.sub(r"[^A-Z0-9]", "", code.upper())


def digest(salt: str, code: str) -> str:
    return hashlib.sha256(("%s|%s" % (salt, normalize(code))).encode("utf-8")).hexdigest()


def ensure_private_is_ignored():
    gi = os.path.join(ROOT, ".gitignore")
    existing = open(gi, encoding="utf-8").read() if os.path.exists(gi) else ""
    if "tools/private/" not in existing:
        with open(gi, "a", encoding="utf-8") as fh:
            fh.write("\n# v45 Roll Call: plaintext activation codes must never be committed\n"
                     "tools/private/\n")
        print("  • added tools/private/ to .gitignore")
    os.makedirs(PRIVATE, exist_ok=True)


def load_existing():
    """Return (salt, [hashes], batch_ids) from the current public list."""
    if not os.path.exists(CODES_JS):
        return secrets.token_hex(8), [], []
    src = open(CODES_JS, encoding="utf-8").read()
    salt = re.search(r'salt:"([^"]+)"', src).group(1)
    lst = re.findall(r'"([0-9a-f]{64})"', src)
    batches = re.findall(r'"([A-Za-z0-9._-]+)"', re.search(r'batches:\[([^\]]*)\]', src).group(1)) \
        if re.search(r'batches:\[([^\]]*)\]', src) else []
    return salt, lst, batches


def make_codes(n, taken):
    out, seen = [], set(taken)
    while len(out) < n:
        body = "".join(secrets.choice(ALPHABET) for _ in range(6))
        code = "MAMSS-%s-%s" % (body, YEAR)
        if normalize(code) in seen:
            continue
        seen.add(normalize(code))
        out.append(code)
    return out


def read_ledger():
    """Keep the previously published ledger config when re-issuing."""
    try:
        src = open(CODES_JS, encoding="utf-8").read()
        m = re.search(r'ledger:\{url:"([^"]+)",key:"([^"]+)"\}', src)
        if m:
            return {"url": m.group(1), "key": m.group(2)}
    except Exception:
        pass
    return None


def write_public(salt, hashes, batches, policy, ledger=None):
    js = ("/* MAMSS PREP — school activation codes: PUBLIC HALF (salted hashes only).\n"
          "   The plaintext list lives offline with the school (tools/private/, git-ignored).\n"
          "   Generated by tools/issue_codes.py — never hand-edit.\n"
          "   Entry is normalised: case and separators are ignored. */\n"
          'window.MAMSS_CODES={v:1,policy:"%s",algo:"sha256",salt:"%s",batches:[%s],count:%d,%s\n'
          "list:[%s]};\n"
          % (policy, salt, ",".join('"%s"' % b for b in batches), len(hashes),
             ('ledger:{url:"%s",key:"%s"},' % (ledger["url"], ledger["key"])) if ledger else "",
             ",".join('"%s"' % h for h in hashes)))
    with open(CODES_JS, "w", encoding="utf-8") as fh:
        fh.write(js)
    return len(js)


def write_private(codes, batch_id, salt):
    stamp = dt.date.today().isoformat()
    csv_path = os.path.join(PRIVATE, "codes-%s-%s.csv" % (batch_id, stamp))
    with open(csv_path, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["code", "hash16", "batch", "issued", "note"])
        for c in codes:
            w.writerow([c, digest(salt, c)[:16], batch_id, stamp, ""])
    html_path = os.path.join(PRIVATE, "codes-%s-%s.html" % (batch_id, stamp))
    slips = "".join(
        '<div class="slip"><b>MAMSS PREP · activation code</b><span class="c">%s</span>'
        '<small>one device · keep it in your exercise book</small></div>' % html.escape(c)
        for c in codes)
    with open(html_path, "w", encoding="utf-8") as fh:
        fh.write("""<!doctype html><html><head><meta charset="utf-8"><title>MAMSS codes · %s</title>
<style>@page{margin:14mm}body{font:14px/1.4 system-ui,sans-serif}
h1{font-size:17px}.slip{display:inline-block;width:74mm;margin:0 4mm 6mm 0;padding:5mm 6mm;
border:1px dashed #999;border-radius:4mm;page-break-inside:avoid}
.slip b{display:block;font-size:9px;letter-spacing:.12em;text-transform:uppercase;color:#666}
.c{display:block;font:700 21px/1.3 ui-monospace,Menlo,Consolas,monospace;letter-spacing:.06em;margin:2mm 0}
small{color:#666;font-size:9px}</style></head><body>
<h1>MAMSS PREP — activation slips · batch %s · %d codes · print and cut</h1>
<p style="color:#666;font-size:11px">PRIVATE. Each code activates one device. This sheet is the only
plaintext copy — store it with the school's records, never upload it.</p>%s</body></html>"""
                 % (batch_id, batch_id, len(codes), slips))
    return csv_path, html_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", type=int, default=120)
    ap.add_argument("--batch", default="batch-" + dt.date.today().strftime("%Y%m%d"))
    ap.add_argument("--ledger-url", default=None, help="Supabase project URL (public by design)")
    ap.add_argument("--ledger-key", default=None, help="Supabase ANON key (public by design; never service_role)")
    ap.add_argument("--policy", choices=["codes", "open"], default="codes",
                    help="codes = new access needs a code (existing signed-in devices unaffected); "
                         "open = codes optional")
    a = ap.parse_args()
    if a.count < 0 or a.count > 5000:
        print("count must be 0..5000 (0 = republish config only)"); return 2
    if a.ledger_url and not a.ledger_key:
        print("--ledger-url needs --ledger-key (the ANON key)"); return 2
    if a.ledger_key and a.ledger_key.startswith("sb_secret"):
        print("that looks like a SECRET key — the site only ever uses the ANON key"); return 4

    ensure_private_is_ignored()
    salt, hashes, batches = load_existing()
    taken_norm = set()
    # we cannot invert hashes, so de-dup by regenerating until unseen; keep a
    # shadow list of previously issued normalised codes if the private folder has them
    for fn in os.listdir(PRIVATE) if os.path.exists(PRIVATE) else []:
        if fn.endswith(".csv"):
            with open(os.path.join(PRIVATE, fn), newline="", encoding="utf-8") as fh:
                for row in csv.DictReader(fh):
                    taken_norm.add(normalize(row["code"]))
    ledger = None
    if a.ledger_url:
        ledger = {"url": a.ledger_url.rstrip("/"), "key": a.ledger_key}
    else:
        ledger = read_ledger()

    if a.count == 0:
        size = write_public(salt, hashes, batches, a.policy, ledger)
        print("\n  config republished: docs/codes.js (%s bytes, %d hashes, ledger %s)"
              % (f"{size:,}", len(hashes), "ON" if ledger else "off"))
        return 0

    codes = make_codes(a.count, taken_norm)
    new_hashes = [digest(salt, c) for c in codes]
    if set(new_hashes) & set(hashes):
        print("  ! collision with existing hashes — aborting"); return 3

    all_hashes = hashes + new_hashes
    batches = batches + [a.batch]
    size = write_public(salt, all_hashes, batches, a.policy, ledger)
    csv_path, html_path = write_private(codes, a.batch, salt)

    print("\n  batch %s: %d new codes · %d total active" % (a.batch, len(codes), len(all_hashes)))
    print("  public  : docs/codes.js (%s bytes, hashes only, ledger %s)"
          % (f"{size:,}", "ON" if ledger else "off"))
    print("  PRIVATE : %s" % csv_path.replace(ROOT + os.sep, ""))
    print("  PRIVATE : %s  (print & cut)" % html_path.replace(ROOT + os.sep, ""))
    print("  sample  : %s" % " · ".join(codes[:4]))
    print("\n  ⚠ tools/private/ must never be committed, uploaded or pasted anywhere.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
